host: "localhost"
port: "8080"
mysql_info:
  user: "root"
  password: "zx1913683154"
  port: "3306"
  db_name: "winter"
redis_info:
  addr: "localhost:6379"
  password: ""
zap_info:
  path: "./zap.txt"
crypt_info:
  key: "0123456789abcdef0123456789abcdef"
  iv: "1234567890123456"
token_secret: "LanshanStudio"